use anyhow::{bail, Context, Result};
use std::fs;
use std::path::Path;

/// Read a single key from a dotenv file without mutating process environment.
pub fn get_env_value(env_path: &Path, key: &str) -> Result<String> {
    let key = key.trim();
    if key.is_empty() {
        bail!(".env 키 이름이 비어 있습니다");
    }
    if !env_path.exists() {
        bail!(
            ".env 파일이 없습니다: {}\n서버를 저장하면 자동 생성됩니다.",
            env_path.display()
        );
    }

    for item in dotenvy::from_path_iter(env_path)
        .with_context(|| format!(".env 읽기 실패: {}", env_path.display()))?
    {
        let (k, v) = item.context(".env 항목 파싱 실패")?;
        if k == key {
            if v.is_empty() {
                bail!(".env 키 '{key}' 값이 비어 있습니다. 파일을 열어 값을 입력하세요.");
            }
            return Ok(v);
        }
    }

    bail!(
        ".env에서 키 '{key}'를 찾지 못했습니다 ({})",
        env_path.display()
    )
}

pub fn env_file_exists(env_path: &Path) -> bool {
    env_path.is_file()
}

/// Create `.env` with a template key if the file does not exist.
/// Returns `true` when a new file was created.
pub fn ensure_env_file(env_path: &Path, env_key: &str) -> Result<bool> {
    let key = if env_key.trim().is_empty() {
        "SSH_PASSWORD"
    } else {
        env_key.trim()
    };

    if env_path.is_file() {
        return Ok(false);
    }

    if let Some(parent) = env_path.parent() {
        if !parent.as_os_str().is_empty() {
            fs::create_dir_all(parent)
                .with_context(|| format!("디렉터리 생성 실패: {}", parent.display()))?;
        }
    }

    let contents = format!(
        "# Auto-generated by Server Manager — fill in the secret value\n\
         # Server credentials for this host only. Do not commit real secrets.\n\
         {key}=\n"
    );
    fs::write(env_path, contents)
        .with_context(|| format!(".env 생성 실패: {}", env_path.display()))?;
    Ok(true)
}
