use crate::secret_crypto::{decrypt_secret, ensure_plaintext_secret, is_encrypted};
use anyhow::{bail, Context, Result};
use std::fs;
use std::path::Path;

/// Read a single key from a dotenv file without mutating process environment.
/// Values are stored as plaintext. Legacy `ENC:v1:...` blobs are decrypted once.
pub fn get_env_value(env_path: &Path, key: &str) -> Result<String> {
    let key = key.trim();
    if key.is_empty() {
        bail!(".env 키 이름이 비어 있습니다");
    }
    if !env_path.exists() {
        bail!(
            ".env 파일이 없습니다: {}\n서버를 저장하면 자동 생성됩니다.",
            env_path.display()
        );
    }

    let raw = fs::read_to_string(env_path)
        .with_context(|| format!(".env 읽기 실패: {}", env_path.display()))?;

    let prefix = format!("{key}=");
    for line in raw.lines() {
        let trimmed = line.trim_start();
        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }
        let Some(rest) = trimmed.strip_prefix(&prefix) else {
            continue;
        };
        let value = unquote_env_raw(rest);
        if value.is_empty() {
            bail!(".env 키 '{key}' 값이 비어 있습니다. 서버를 수정해 암호를 다시 저장하세요.");
        }
        // Legacy encrypted values from older builds
        if is_encrypted(&value) {
            return decrypt_secret(&value, key);
        }
        return Ok(value);
    }

    bail!(
        ".env에서 키 '{key}'를 찾지 못했습니다 ({})",
        env_path.display()
    )
}

pub fn env_file_exists(env_path: &Path) -> bool {
    env_path.is_file()
}

fn format_assignment(key: &str, value: &str) -> String {
    if value.is_empty() {
        return format!("{key}=");
    }
    // Prefer single quotes so `$` / spaces are preserved literally.
    let needs_quotes = value.chars().any(|c| {
        c.is_whitespace()
            || c == '#'
            || c == '"'
            || c == '\''
            || c == '='
            || c == '$'
            || c == '\\'
    });
    if !needs_quotes {
        return format!("{key}={value}");
    }
    if !value.contains('\'') {
        return format!("{key}='{value}'");
    }
    format!(
        "{key}=\"{}\"",
        value
            .replace('\\', "\\\\")
            .replace('"', "\\\"")
            .replace('\n', "\\n")
            .replace('\r', "")
    )
}

fn unquote_env_raw(raw: &str) -> String {
    let s = raw.trim();
    if s.is_empty() {
        return String::new();
    }

    let bytes = s.as_bytes();
    if bytes[0] == b'\'' {
        let mut out = String::new();
        let b = s.as_bytes();
        let mut i = 1;
        while i < b.len() {
            if b[i] == b'\'' {
                break;
            }
            out.push(b[i] as char);
            i += 1;
        }
        return out;
    }

    if bytes[0] == b'"' {
        let mut out = String::new();
        let mut i = 1;
        let b = s.as_bytes();
        while i < b.len() {
            match b[i] {
                b'"' => break,
                b'\\' if i + 1 < b.len() => {
                    match b[i + 1] {
                        b'n' => out.push('\n'),
                        b'\\' => out.push('\\'),
                        b'"' => out.push('"'),
                        b'\'' => out.push('\''),
                        b'$' => out.push('$'),
                        b' ' => out.push(' '),
                        other => {
                            out.push('\\');
                            out.push(other as char);
                        }
                    }
                    i += 2;
                }
                c => {
                    out.push(c as char);
                    i += 1;
                }
            }
        }
        return out;
    }

    if let Some(idx) = s.find(" #") {
        return s[..idx].trim_end().to_string();
    }
    s.to_string()
}

/// Create `.env` with a template key if the file does not exist.
/// Returns `true` when a new file was created.
pub fn ensure_env_file(env_path: &Path, env_key: &str) -> Result<bool> {
    let key = if env_key.trim().is_empty() {
        "SSH_PASSWORD"
    } else {
        env_key.trim()
    };

    if env_path.is_file() {
        return Ok(false);
    }

    if let Some(parent) = env_path.parent() {
        if !parent.as_os_str().is_empty() {
            fs::create_dir_all(parent)
                .with_context(|| format!("디렉터리 생성 실패: {}", parent.display()))?;
        }
    }

    let contents = format!(
        "# Auto-generated by Server Manager — per-server credentials\n\
         # Store the secret in plaintext. Do not commit this file.\n\
         {key}=\n"
    );
    fs::write(env_path, contents)
        .with_context(|| format!(".env 생성 실패: {}", env_path.display()))?;
    Ok(true)
}

/// Ensure the file exists and set/update `env_key` to a plaintext `value`.
/// Returns whether the file was newly created.
pub fn upsert_env_value(env_path: &Path, env_key: &str, value: &str) -> Result<bool> {
    let key = if env_key.trim().is_empty() {
        "SSH_PASSWORD"
    } else {
        env_key.trim()
    };

    let created = ensure_env_file(env_path, key)?;
    ensure_plaintext_secret(value)?;
    let assignment = format_assignment(key, value);

    let raw = fs::read_to_string(env_path)
        .with_context(|| format!(".env 읽기 실패: {}", env_path.display()))?;

    let prefix = format!("{key}=");
    let mut replaced = false;
    let mut lines: Vec<String> = Vec::new();
    for line in raw.lines() {
        let trimmed = line.trim_start();
        if !replaced && !trimmed.starts_with('#') && trimmed.starts_with(&prefix) {
            lines.push(assignment.clone());
            replaced = true;
        } else {
            lines.push(line.to_string());
        }
    }
    if !replaced {
        if !lines.is_empty() && !lines.last().map(|l| l.is_empty()).unwrap_or(true) {
            lines.push(String::new());
        }
        lines.push(assignment);
    }
    lines.push(String::new());

    fs::write(env_path, lines.join("\n"))
        .with_context(|| format!(".env 쓰기 실패: {}", env_path.display()))?;
    Ok(created)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::time::{SystemTime, UNIX_EPOCH};

    #[test]
    fn env_roundtrip_password() {
        let stamp = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        let path = std::env::temp_dir().join(format!("sm-env-test-{stamp}.env"));
        let _ = fs::remove_file(&path);

        upsert_env_value(&path, "SSH_PASSWORD", "s3cret!#@$").expect("upsert");
        let raw = fs::read_to_string(&path).unwrap();
        assert!(!raw.contains("ENC:v1:"), "raw={raw}");
        assert!(raw.contains("SSH_PASSWORD="), "raw={raw}");

        let got = get_env_value(&path, "SSH_PASSWORD").expect("get");
        assert_eq!(got, "s3cret!#@$");
        let _ = fs::remove_file(&path);
    }
}
